# Generated by Django 4.2.5 on 2023-09-11 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
