# Generated by Django 4.2.5 on 2023-09-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskManagement", "0002_project_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("finished", "Finished")],
                default="active",
                max_length=20,
            ),
        ),
    ]
